spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:

  liquibase:
    change-log: classpath:db/changelog/db.master-changelog.xml

  datasource:
    url: jdbc:postgresql://localhost:5432/db_complaints
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs

# Resilience4j configuration
resilience4j:
  circuitbreaker:
    instances:
      geoLocationService:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
  retry:
    instances:
      geoLocationServiceRetry:
        max-attempts: 3
        wait-duration: 500ms

